### ISSUE TITLE
Delete process API doesn't work as expected

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/grid#106]
## Steps: 
 - Delete process with API { /nodes/{nodeid}/processes/{processid }
- Try to get this process again
## Expected result 
- deleted process should not be found  again 
## Actual result : 
- you can get the process again and it founded in processes list 
![selection_287](https://cloud.githubusercontent.com/assets/24386802/25192330/16b08842-2533-11e7-8b87-be0a4b37d335.png)
![selection_288](https://cloud.githubusercontent.com/assets/24386802/25192333/1b35c9fe-2533-11e7-8972-5c763f05a5b4.png)

**Comment by serboctor** [comment]
The kernel processes don't die even if sigkill is used.
I refactored the api to send the sigterm 3 times and if the process doesn't die, it will send sigkill to the process. If the process still exists, it will return an appropraite error message.
The same change was done to KillContainerProcess.

**Comment by Dinaamagdy** [comment]
commit : f653c14e04a1e49ea0ce4608781b4fba14456889
