### ISSUE TITLE
Create container responce is in header not in body

### ISSUE THREAD

**Issue by islamTaha12** [g8os/grid#109]
The response of creating the new container is in header not in the body. It should be in the response.json()

![screenshot from 2017-04-20 13-01-19](https://cloud.githubusercontent.com/assets/17981089/25227652/0ad443a2-25d2-11e7-8c1f-adcf0dbfd771.png)

**version**
1.1.0-alpha

**Comment by zaibon** [comment]
This is conform to the API specs. Location in the header, nothing in body.
