### ISSUE TITLE
invalid syntax when executing discover node blueprint 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#117]
![image](https://cloud.githubusercontent.com/assets/24386820/25312591/b52d9914-281d-11e7-9aba-c7bacf0c93ed.png)

**Comment by rkhamis** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_core8/commit/e468b56f2d5857383064d0c68f5088e69b7ed13b
