### ISSUE TITLE
containers_api : killalljobs

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [g8os/grid#121]
## Reproduce 
```REST
delete http://{{url}}/nodes/:node_name/containers/:container_id/jobs
```
kill all jobs in container api always returns a 500.

## Response 500
{
  "error": "Error getting service 0"
}

**Comment by serboctor** [comment]
I couldn't reproduce this exact error. However, I got another error which I fixed. The fix for this requires updates the go-client.
