### ISSUE TITLE
vms_apis: get vm details doesn't return the actual vm status when vm status is paused

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#127]
### API
```GET /nodes/{nodeid}/vms/{vmid}```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25431272/2c94f9a2-2a80-11e7-99ff-929eccfcacf1.png)

### Actual result
**grid api response** 
![image](https://cloud.githubusercontent.com/assets/24386820/25431315/56ec02ea-2a80-11e7-80bf-461c284fac5c.png)
**python client** 
![image](https://cloud.githubusercontent.com/assets/24386820/25431348/7c430052-2a80-11e7-8950-3e713ac8837b.png)

**Comment by serboctor** [comment]
Depends on #139

**Comment by ahmedelsayed-93** [comment]
### Software Versions
grid ```ab035b1```
jumpscale_core8 ```9944c96 ```
