### ISSUE TITLE
storagepool api: GET device list/details for a storage pool that doesn't exist returns 500 instead of 404

### ISSUE THREAD

**Issue by serboctor** [g8os/grid#133]
Do
GET /nodes/{nodeid}/storagepools/{storagepoolname}/devices
or
GET /nodes/{nodeid}/storagepools/{storagepoolname}/devices/{deviceuuid}

for a storagepoolname that doesn't exist and it will return a 500 instead of 404

**Comment by ahmedelsayed-93** [comment]
### Software versions

grid : ```abcf275```
jumpscale_core8 : ```9e43171```
