### ISSUE TITLE
vdisks_apis: list vdisks returns empty values

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#137]
### API
```GET /vdisks```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25475793/42d2ce5c-2b38-11e7-8223-054d75b724f9.png)

storageCluster & type parameters are empty

**Comment by grimpy** [comment]
Fixed by https://github.com/g8os/grid/pull/148/files

**Comment by ahmedelsayed-93** [comment]
###software version
grid faeae03
jumpscale 92c7a2d
