### ISSUE TITLE
Implement flist build actor for g8os grid api service

### ISSUE THREAD

**Issue by FastGeert** [g8os/grid#32]
Python3+Sanic+Caddy+AYS Server+JS8+g8os grid api server

The actor should build the tar gz and upload it to hub.gig.tech automatically

CoreX images build by means of AYS82 / cuisine / docker on top of packet.net

**Comment by maxux** [comment]
https://github.com/g8os/grid/blob/0.2.0/buildscripts/builder-g8os-grid.sh
