### ISSUE TITLE
Implement zerotier REST API

### ISSUE THREAD

**Issue by zaibon** [g8os/grid#45]

**Comment by ahmedelsayed-93** [comment]
can't join zerotier network

### API
``` nodes/{nodeid}/zerotiers```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25341872/9b9bb6fa-290a-11e7-9621-34ea5a1efb4e.png)

**Comment by ahmedelsayed-93** [comment]
### Software versions
grid : abcf275
jumpscale_core8 : 9e43171
