### ISSUE TITLE
Ability to know the storagecluster from a volumeid

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/grid#51]

**Comment by ahmedelsayed-93** [comment]
verification process is blocked because of https://github.com/g8os/grid/issues/112

**Comment by ahmedelsayed-93** [comment]
verification process is blocked because of https://github.com/g8os/grid/issues/112

**Comment by ahmedelsayed-93** [comment]
check this issue 
https://github.com/g8os/grid/issues/137
