### ISSUE TITLE
Automated g8 grid controller setup

### ISSUE THREAD

**Issue by FastGeert** [g8os/grid#61]
We need a script in which we can pass a number of configuration arguments that will result in a usb image to boot up the controller 

## Steps

1. Generate g8os usb image with integrated setup
    - Networking setup
    - Bootstrap script that automatically starts the AYS Server
        - Ays repo

2. Bootup controller with usb stick containing image built in step 1
3. Auto start script that will setup the AYS Server container
4. AYS Server will setup Grid api server, pxe boot server, influx db server

**Comment by despiegk** [comment]
- is too big, lets discuss
- g8os needs to be minimal

**Comment by despiegk** [comment]
will not do see
https://github.com/g8os/core0/blob/despiegk-patch-1/specs/bootstrap.md

**Comment by maxux** [comment]
# Bootstrapping
- Grab your ZeroTier Network ID
- Get your iPXE boot script from (demo url): `http://stor.jumpscale.org/g8os/ipxe?network=NETWORKID`
- AYS Server (wherever you want) will check the ZeroTier Network Members and update internally the knows hosts.
