### ISSUE TITLE
Implementation for ays nodes boostrap service

### ISSUE THREAD

**Issue by FastGeert** [g8os/grid#7]
See specifications created by https://github.com/g8os/grid/issues/6

**Comment by zaibon** [comment]
Added documentation about autodiscovery for core0 : https://github.com/g8os/core0/commit/90ce14378f92bf00f45ee8322438c2a67f698fe8

and the script is added to the initramfs repo with our custom config: 
https://github.com/g8os/initramfs/commit/eca339e572f39b66c3ef0b87fdf78b24749aafa5
