### ISSUE TITLE
confusing Argument in create container api 

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/grid#70]
![selection_282](https://cloud.githubusercontent.com/assets/24386802/24954593/5578a856-1f80-11e7-911b-1b6c4d22feae.png)

#### id  -> should be container name 

![selection_281](https://cloud.githubusercontent.com/assets/24386802/24954664/942a0ff4-1f80-11e7-9bab-010a61c49b26.png)

**Comment by FastGeert** [comment]
The grid does not generate ids.
