### ISSUE TITLE
all apis with method post return error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#72]
![image](https://cloud.githubusercontent.com/assets/24386820/24969052/ba591ab0-1faf-11e7-9ed3-bc0fb27ec6b1.png)

### SV
JUMPSACLE_BRANCH = "8.2.0"
GRID_API_BRANCH = "1.1.0-alpha"
AYS_TEMPLATE_BRANCH = "0.2.0"

**Comment by grimpy** [comment]
Fixed in lastest version
