### ISSUE TITLE
Grid API can't reache API server any more

### ISSUE THREAD

**Issue by islamTaha12** [g8os/grid#88]
Steps :
- Create vm1 with (js 8.2.0 - g8core - start AYS - clone ays template branch 1.1.0-alpha)
- Create vm2 with grid api version 1.1.0-alpha then
- run (/opt/code/bin/api --bind :8080 --ays-url http://192.168.103.254:5000 --ays-repo grid) 

Actual result:
**Ays**
![image](https://cloud.githubusercontent.com/assets/17981089/25137258/eda1a25c-245f-11e7-9c9d-4a712efc5905.png)

**Grid API**
![image](https://cloud.githubusercontent.com/assets/17981089/25137224/ca3b3166-245f-11e7-9a0d-93a67e54845d.png)

**Hint**
seems that the sanic team did an update yesterday
https://github.com/channelcat/sanic

**Comment by zaibon** [comment]
so the proble was indeed wrong sanic version.
Fix in https://github.com/Jumpscale/jumpscale_core8/commit/d8a2f31447e422389bcbcfa90e38d075ed3a8e9f
