### ISSUE TITLE
vms_apis: Delete vm returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#91]
### API
```DELETE /nodes/{nodeid}/vms/{vmid}```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25175688/0d20b090-24fc-11e7-849e-73e099d12043.png)

response
```>>>future exception None\n\njob job: node.g8os!0cc47ae54774 (start) done sucessfuly\n\nstop vm vm1\n\n>>>>future exception 'Client' object has no attribute 'kvm'\n\nAttributeError: 'Client' object has no attribute 'kvm'\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.5/concurrent/futures/thread.py\", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/tmp/actions/vm/ae50b6f7cb846098106055987869b79c.py\", line 215, in stop\n    kvm = get_domain(service)\n  File \"/tmp/actions/vm/ae50b6f7cb846098106055987869b79c.py\", line 250, in get_domain\n    for kvm in client.kvm.list():\nAttributeError: 'Client' object has no attribute 'kvm```

### Software version

- Grid API : "1.1.0-alpha"
- JS : 8.2.0
- G8OS : https://bootstrap.gig.tech/kernel/g8os-1.1.0-alpha.efi

**Comment by serboctor** [comment]
This error means the python client needs to be updated. I tried to create and delete a vm and it went smoothly. However, my vm didn't have any disks.
