### ISSUE TITLE
storagepools_api: get storagepool's device by uuid returns empty values

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#94]
### API
```GET /nodes/{nodeid}/storagepools/{storagepoolname}/devices/{deviceuuid} ```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25178508/54316f92-2506-11e7-9186-a95724f7673e.png)

### SV
- Grid API : "1.1.0-alpha"
- JS : 8.2.0
- G8OS : https://bootstrap.gig.tech/kernel/g8os-1.1.0-alpha.efi

**Comment by serboctor** [comment]
Status is not implemented yet and there is a separate issue for it. I fixed all the other fields.
https://github.com/g8os/grid/issues/93

**Comment by ahmedelsayed-93** [comment]
### Software versions

grid : ```abcf275```
jumpscale_core8 : ```9e43171```
