### ISSUE TITLE
Disks API, always return empty value in type, and 0 in size parameters

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/grid#95]
## Steps: 
use API : get /nodes/{nodeid}/disks
## Response : 
![selection_285](https://cloud.githubusercontent.com/assets/24386802/25179018/6daec508-2508-11e7-945a-99dd6847d892.png)

**Comment by serboctor** [comment]
Fixed the size and type. Also, the mountpoint and opts will be empty if this disk is not mounted. And fstype if there is no file system on this disk.

**Comment by ahmedelsayed-93** [comment]
size still 0 
![image](https://cloud.githubusercontent.com/assets/24386820/25314511/b7f9703c-2845-11e7-8d7c-598e7fb98b80.png)

although the size of the disk is 74.5 GB
![image](https://cloud.githubusercontent.com/assets/24386820/25314516/d9aee5d6-2845-11e7-8038-2cc6c70164da.png)

**Comment by Dinaamagdy** [comment]
commit : f653c14e04a1e49ea0ce4608781b4fba14456889
